server:
  port: 8085

security:
  resource-id: "asset.application"
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1t9wCc2TG91cvSOUCJAz
          5xWJxYaxgpQfz+H5GWqUWIrU2SDpwrLd9ewIKjdxcaMSDeLb3ydP0a8WyWvUbBna
          A2vG3QdL+2D+9qKOnbT5FIttHwKWjElEl3zAHtyDi2J+bRbX3sUJPTmkPv5Yu9ir
          hB9riy5U3GygaAy4nkvPYuO5XW9izGR5pdsfJmabNEgUScxKp3ns3f0DOHFkZCoo
          yuSDFDQMYNSMcPHRZjU8BpSXqOYfO/y3QFIagnaMFlIyWcyRXVN1o25z9sVZuJn+
          k+gTskfgBW/ttR553VaxfP/r5qd7zeRF2BO6mTLcIqyNeadwxou1JfC1GEJDeKW9
          qQIDAQAB
          -----END PUBLIC KEY-----
spring:
  datasource:
    validation-query: SELECT 1
    max-active: 10
    max-idle: 8
    min-idle: 8
    initial-size: 5
    test-on-borrow: true
    test-on-return: true
    url: "jdbc:h2:~/test"
    driver-class-name: org.h2.Driver
    username: asset
    password: asset

logging:
  config: "classpath:log4j2dev.properties"

jooq:
  sql:
    dialect: H2

pool:
  bio:
    core-size: 5
    max-size: 20
    alive-time: 100